
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = false }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@60.01Hz",
    position = "0x0",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "ghostty"
local fileManager = "thunar"
local menu        = "walker"
local browser     = "flatpak run app.zen_browser.zen"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
  hl.exec_cmd("elephant")
  hl.exec_cmd("swaybg -i /home/kavin/Downloads/wallpaper -m fill")
  hl.exec_cmd("walker --gapplication-service")
  hl.exec_cmd("waybar")
  hl.exec_cmd("ags run -d /home/kavin/.config/ags")
  hl.exec_cmd("nm-applet")
  hl.exec_cmd("snappy-switcher --daemon -c /home/kavin/.config/snappy-switcher/config.ini")
  hl.exec_cmd("/usr/lib/gnome-keyring-daemon --start --components=secrets,ssh,pkcs11")
  hl.exec_cmd("qs -c tray")
  hl.exec_cmd("sh -c '/home/kavin/.config/hypr/scripts/start-wob.sh'")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("AQ_DRM_DEVICES", "/dev/dri/card1:/dev/dri/card0")
hl.env("LIBVA_DRIVER_NAME", "iHD")
hl.env("VDPAU_DRIVER", "va_gl")
hl.env("GDK_BACKEND", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "mesa")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 2,
        gaps_out = 2,

        border_size =1,

        col = {
            active_border   = { colors = {"rgba(4A9EF1ff)", "rgba(00FFF0ff)"}, angle = 45 },
            inactive_border = "rgba(2D2D30ff)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 5,    bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 3,    bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 2.5,  spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = false })
hl.animation({ leaf = "windowsOut",    enabled = false })
hl.animation({ leaf = "fadeIn",        enabled = false })
hl.animation({ leaf = "fadeOut",       enabled = false })
hl.animation({ leaf = "fade",          enabled = false })
hl.animation({ leaf = "layers",        enabled = true,  speed = 2,    bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 2,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 0.8,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 0.9,  bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 0.7,  bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1,    bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 0.6,  bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1,    bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 4,    bezier = "quick" })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "caps:escape",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Core binds
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))   -- terminal
hl.bind(mainMod .. " + Q",      hl.dsp.window.close())        -- close window
hl.bind(mainMod .. " + W",      hl.dsp.window.close())        -- close window (alt)
hl.bind(mainMod .. " + B",      hl.dsp.exec_cmd(browser))     -- default browser
hl.bind(mainMod .. " + M",      hl.dsp.exec_cmd("hyprctl dispatch exit")) -- exit hyprland
hl.bind(mainMod .. " + E",      hl.dsp.exec_cmd(fileManager)) -- file manager
hl.bind(mainMod .. " + R",      hl.dsp.exec_cmd(menu))        -- app launcher
hl.bind(mainMod .. " + V",      hl.dsp.window.float({ action = "toggle" })) -- toggle float
hl.bind(mainMod .. " + D",      hl.dsp.exec_cmd("/home/kavin/.config/hypr/scripts/show-desktop.sh")) -- show desktop

-- Window management
hl.bind(mainMod .. " + P",      hl.dsp.window.pseudo())       -- dwindle pseudo
hl.bind(mainMod .. " + J",      hl.dsp.layout("togglesplit")) -- dwindle toggle split
hl.bind("ALT + space",           hl.dsp.exec_cmd(menu))        -- app launcher (walker)
hl.bind(mainMod .. " + space",   hl.dsp.exec_cmd(menu))        -- app launcher (walker)
hl.bind(mainMod .. " + TAB",    hl.dsp.exec_cmd("hyprctl dispatch swapwithmaster")) -- swap with master

-- Move focus with mainMod + HJKL (vim-style)
hl.bind(mainMod .. " + h",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l",  hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k",  hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j",  hl.dsp.focus({ direction = "down" }))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Fullscreen & layout
hl.bind(mainMod .. " + F",           hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" })) -- fullscreen
hl.bind(mainMod .. " + SHIFT + F",   hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })) -- maximize

-- Alt keybinds
hl.bind("ALT + Return",              hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })) -- maximize

-- Alt+Tab window switching with snappy-switcher
hl.bind("ALT + Tab",                 hl.dsp.exec_cmd("snappy-switcher next --mod alt"))
hl.bind("ALT + SHIFT + Tab",         hl.dsp.exec_cmd("snappy-switcher prev --mod alt"))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", function() hl.dispatch(hl.dsp.window.drag()) end,   { mouse = true })
hl.bind(mainMod .. " + mouse:273", function() hl.dispatch(hl.dsp.window.resize()) end, { mouse = true })

-- Trackpad-friendly: use keyboard keys instead of mouse clicks
hl.bind(mainMod .. " + Control_L", function() hl.dispatch(hl.dsp.window.drag()) end,   { mouse = true })
hl.bind(mainMod .. " + Alt_L",     function() hl.dispatch(hl.dsp.window.resize()) end, { mouse = true })

-- Windows-style workspace switching: Win + Ctrl + Left/Right
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.focus({ workspace = "e+1" }))

-- Move window to prev/next workspace: Win + Shift + Left/Right
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ workspace = "e+1" }))

-- Create new workspace: Win + Ctrl + D
hl.bind(mainMod .. " + CTRL + D", hl.dsp.exec_cmd("~/.config/hypr/scripts/workspace-new.sh"))

-- Close current workspace: Win + Ctrl + F4
hl.bind(mainMod .. " + CTRL + F4", hl.dsp.exec_cmd("~/.config/hypr/scripts/workspace-close.sh"))

-- Quick workspace navigation (bracket keys as alt)
hl.bind(mainMod .. " + bracketleft",  hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + bracketright", hl.dsp.focus({ workspace = "e+1" }))

-- Scratchpad (Win + S)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))

-- Screenshot (Win + Shift + S)
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot-ksnip.sh"))

-- Keep workspaces 1-5 alive even when empty
for i = 1, 5 do
    hl.workspace_rule({ workspace = tostring(i), persistent = true })
end

-- Create 5 persistent workspaces at startup
hl.on("hyprland.start", function ()
    hl.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"2\"})'")
    hl.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"3\"})'")
    hl.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"4\"})'")
    hl.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"5\"})'")
    hl.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"1\"})'")
end, { once = true })

-- Switch workspaces with mainMod + [1-5]
-- Move active window to a workspace with mainMod + SHIFT + [1-5]
hl.bind(mainMod .. " + 1", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"1\"})'"))
hl.bind(mainMod .. " + 2", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"2\"})'"))
hl.bind(mainMod .. " + 3", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"3\"})'"))
hl.bind(mainMod .. " + 4", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"4\"})'"))
hl.bind(mainMod .. " + 5", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.focus({workspace=\"5\"})'"))
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.window.move({workspace=\"1\"})'"))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.window.move({workspace=\"2\"})'"))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.window.move({workspace=\"3\"})'"))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.window.move({workspace=\"4\"})'"))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.exec_cmd("hyprctl dispatch 'hl.dsp.window.move({workspace=\"5\"})'"))

-- Scroll through workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("/home/kavin/.config/hypr/scripts/osd-volume.sh up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("/home/kavin/.config/hypr/scripts/osd-volume.sh down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("/home/kavin/.config/hypr/scripts/osd-volume.sh mute"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("/home/kavin/.config/hypr/scripts/osd-brightness.sh up"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("/home/kavin/.config/hypr/scripts/osd-brightness.sh down"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
