vim.cmd("highlight clear")
vim.g.colors_name = "obsidian-purple"
if vim.g.obsidian_transparent == nil then vim.g.obsidian_transparent = true end
local c = {
  bg = "#09070d", surface = "#17101f", border = "#382447", fg = "#eee6f7",
  muted = "#927da6", purple = "#b58cff", pale = "#d6beff", green = "#9dc6ad",
  red = "#ee8ca6", orange = "#ddb18c", blue = "#9baee3", yellow = "#dbcc99",
}
local base = vim.g.obsidian_transparent and "NONE" or c.bg
local groups = {
  Normal = { fg = c.fg, bg = base }, NormalNC = { fg = c.fg, bg = base },
  SignColumn = { bg = base }, EndOfBuffer = { fg = c.border, bg = base },
  NormalFloat = { fg = c.fg, bg = c.surface }, FloatBorder = { fg = c.purple, bg = c.surface },
  FloatTitle = { fg = c.pale, bg = c.surface, bold = true }, WinSeparator = { fg = c.border },
  LineNr = { fg = c.border }, CursorLineNr = { fg = c.purple, bold = true },
  CursorLine = { bg = c.surface }, ColorColumn = { bg = c.surface },
  Visual = { bg = c.border }, Search = { fg = c.bg, bg = c.pale },
  IncSearch = { fg = c.bg, bg = c.purple }, CurSearch = { fg = c.bg, bg = c.purple },
  MatchParen = { fg = c.pale, bg = c.border, bold = true },
  Pmenu = { fg = c.fg, bg = c.surface }, PmenuSel = { fg = c.bg, bg = c.purple },
  PmenuSbar = { bg = c.border }, PmenuThumb = { bg = c.muted },
  StatusLine = { fg = c.pale, bg = c.surface }, StatusLineNC = { fg = c.muted, bg = c.bg },
  TabLine = { fg = c.muted, bg = c.bg }, TabLineSel = { fg = c.purple, bg = c.surface },
  TabLineFill = { bg = c.bg }, Folded = { fg = c.muted, bg = c.surface },
  NonText = { fg = c.border }, Whitespace = { fg = c.border },
  Comment = { fg = c.muted, italic = true }, String = { fg = c.green },
  Character = { fg = c.green }, Number = { fg = c.orange }, Boolean = { fg = c.orange },
  Float = { fg = c.orange }, Constant = { fg = c.orange }, Identifier = { fg = c.fg },
  Function = { fg = c.pale }, Statement = { fg = c.purple }, Keyword = { fg = c.purple },
  Conditional = { fg = c.purple }, Repeat = { fg = c.purple }, Exception = { fg = c.purple },
  Type = { fg = c.blue }, PreProc = { fg = c.purple }, Special = { fg = c.yellow },
  Operator = { fg = c.pale }, Delimiter = { fg = c.muted }, Title = { fg = c.purple, bold = true },
  Directory = { fg = c.purple }, Error = { fg = c.red }, ErrorMsg = { fg = c.red },
  WarningMsg = { fg = c.orange }, MoreMsg = { fg = c.green }, Question = { fg = c.purple },
  Todo = { fg = c.yellow, bold = true },
  DiagnosticError = { fg = c.red }, DiagnosticWarn = { fg = c.orange },
  DiagnosticInfo = { fg = c.blue }, DiagnosticHint = { fg = c.pale },
  DiagnosticUnderlineError = { sp = c.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
  DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
  DiagnosticUnderlineHint = { sp = c.pale, undercurl = true },
  DiffAdd = { bg = "#18291f" }, DiffDelete = { bg = "#301820" }, DiffChange = { bg = "#211932" },
  DiffText = { bg = c.border }, GitSignsAdd = { fg = c.green },
  GitSignsChange = { fg = c.purple }, GitSignsDelete = { fg = c.red },
  TelescopeBorder = { fg = c.border }, TelescopePromptBorder = { fg = c.purple },
  TelescopeSelection = { bg = c.border }, TelescopeMatching = { fg = c.purple, bold = true },
  MiniStarterHeader = { fg = c.purple, bold = true }, MiniStarterFooter = { fg = c.muted },
  MiniStarterSection = { fg = c.pale }, MiniStarterItemPrefix = { fg = c.purple },
  MiniStarterQuery = { fg = c.green }, MiniStatuslineModeNormal = { fg = c.bg, bg = c.purple, bold = true },
  MiniStatuslineModeInsert = { fg = c.bg, bg = c.green, bold = true },
  MiniStatuslineModeVisual = { fg = c.bg, bg = c.orange, bold = true },
  MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
  MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
  MiniStatuslineModeOther = { fg = c.bg, bg = c.blue, bold = true },
  MiniStatuslineDevinfo = { fg = c.pale, bg = c.border },
  MiniStatuslineFilename = { fg = c.fg, bg = c.surface },
  MiniStatuslineFileinfo = { fg = c.pale, bg = c.border },
  MiniStatuslineInactive = { fg = c.muted, bg = c.bg },
  OilDir = { fg = c.purple }, OilDirIcon = { fg = c.purple },
  WhichKey = { fg = c.purple }, WhichKeyGroup = { fg = c.pale },
}
for group, value in pairs(groups) do vim.api.nvim_set_hl(0, group, value) end
for group, link in pairs({
  ["@variable"] = "Identifier", ["@variable.builtin"] = "Special", ["@variable.parameter"] = "Identifier",
  ["@property"] = "Identifier", ["@keyword"] = "Keyword", ["@function"] = "Function",
  ["@function.builtin"] = "Function", ["@type"] = "Type", ["@module"] = "Type",
  ["@markup.heading"] = "Title", ["@markup.link"] = "Underlined",
}) do vim.api.nvim_set_hl(0, group, { link = link }) end
